name: Compile
on:
  push:
    branches: [ master ]
    tags:
      - '!v*'
jobs:
  Run-Compilation-And-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run cdk