name: Compile
on:
  push:
    branches: [ master ]
    tags:
      - '!v*'
jobs:
  Run-Compilation-And-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2.1.1
        with:
          cdk_subcommand: 'synth'
          cdk_version: '2.23.0'
          working_dir: 'src/example'